components/footer.js, components/header.js, components/headerNav.js, components/hero.js, components/userMenu.js, package-lock.json, package.json, pages/_app.js, styles/globals.css
This PR provides significant improvements to the UI:
- Integrates squareone's UI with rubin-style-dictionary's component design tokens
- Integrates with next-themes to implement dark/light mode. Current light or dark mode is based on the user's system UI preference.
- Use font-awesome to provide a downward chevron affordance for the user login menu.
=> DM-29251: Dark mode and general UI

Dockerfile
This module is critical because it's used to load the configuration file. Without it, the baseUrl is not set, and the app won't start up.
=> DM-29432: Add next.config.js to Docker image

next.config.js
`path.join()` doesn't do anything special if both paths are absolute, so instead this ternary expression ensures that the configuration path is only treated as relative if it fails `path.isAbsolute`.
=> DM-29432: Ensure config path is absolute

components/meta.js, package-lock.json, package.json, pages/_app.js, pages/index.js
This change allows us to package and deliver Source Sans Pro from the app itself rather than relying on a third-party service (Google Fonts).
Also solves a bug related to the default next favicon.
=> DM-29972: Switch to Font Source from Google Fonts

CHANGELOG.rst, README.rst, components/broadcastBanner.js, components/page.js, hooks/fetch.js, package-lock.json, package.json, pages/_app.js, squareone.config.schema.json, squareone.config.yaml
This replaces the previous work to obtain broadcast messages from the app's configuration. Now the Page component uses a `useFetch` hook to obtain broadcasts from Semaphore's `GET /v1/broadcasts` endpoint. Since multiple broadcasts can be active, we map over the broadcasts, creating a `BroadcastBanner` component for each.
The broadcast also makes use of a disclosure widget to "show more" when the message contains additional content beyond just the summary. This widget is powered by https://github.com/KittyGiraudel/react-a11y-disclosure
=> DM-30727: Display broadcasts from Semaphore's REST API

CHANGELOG.rst, src/components/BroadcastBannerStack/BroadcastBanner.js
Add support for broadcast message categories and display broadcasts differently based on that category.
In this initial support, "info" messages are displayed in Rubin primary teal. The default is to show the message using the "maintenance" category display, which is red.
=> DM-34437: Show "info" broadcast messages in Rubin teal

package-lock.json, package.json
Updating husky, eslint, source-sans-pro and next-themes.
Not updating reach-ui/button to 0.17 because it seems to not be compatible with React 17 anymore, which might be accidental. Waiting for an upstream fix. Also delaying the update to React 18 until its well supported by Next.
=> DM-34723: Refresh dependencies

CHANGELOG.rst, next.config.js, package-lock.json, squareone.config.schema.json, squareone.config.yaml, src/components/Page/Page.js, src/components/TimesSquareViewer/TimesSquareViewer.js, src/components/TimesSquareViewer/index.js, src/components/TimesSquareViewer/useHtmlStatus.js, src/pages/_app.js, src/pages/api-aspect.js, src/pages/api/dev/times-square/v1/pages.js, src/pages/api/dev/times-square/v1/pages/[page].js, src/pages/api/dev/times-square/v1/pages/[page]/html.js, src/pages/api/dev/times-square/v1/pages/[page]/htmlstatus.js, src/pages/docs.js, src/pages/index.js, src/pages/login.js, src/pages/logout.js, src/pages/support.js, src/pages/terms.js, src/pages/times-square/index.js, src/pages/times-square/nb/[nbSlug].js
This ports the UI for Times Square from https://github.com/lsst-sqre/times-square-ui
Times Square features can now be enabled by setting the `timesSquareUrl` configuration. If that configuration is `null`, Times Square functionality is disabled (pages return 404).
=> DM-34723: Port from lsst-sqre/times-square-ui

src/components/TimesSquareApp/TimesSquareApp.js, src/components/TimesSquareGitHubPagePanel/TimesSquareGitHubPagePanel.js, src/components/TimesSquareNotebookViewer/TimesSquareNotebookViewer.js, src/components/TimesSquareNotebookViewer/useHtmlStatus.js, src/components/TimesSquareParameters/TimesSquareParameters.js, src/pages/times-square/github/[...tsSlug].js
Adds a checkbox to toggle the `?ts_hide_code` query parameter to 1 or 0, related to https://github.com/lsst-sqre/times-square/pull/33
Generally adds support for display settings (introduced in https://github.com/lsst-sqre/times-square/pull/33), which are a different category of information that's also present in Times Square URL query strings.
=> DM-35057: Add support for hide code cells display param

CHANGELOG.rst, package.json, squareone.config.schema.json, squareone.config.yaml, src/components/Header/UserMenu.js
This allows a deployer to optionally add a `coManageRegistryUrl` setting for deployments that use COmanage. If set, an "Account settings" link appears in their user menu.
=> DM-38116: Add coManageRegistryUrl setting and menu link

.github/workflows/release.yaml
Since .npmrc exists in the repo, changesets/action won't replace it.
Therefore we aren't logged into the github package registry.
=> DM-40262: Authenticate to gh package registry in release

.changeset/config.json, docs/packages/rubin-style-dictionary/installation.rst
This means that we'll get the needed tag for the Squareone release
=> DM-40262: Configure changesets to tag private packages

.changeset/strange-doors-relate.md, .changeset/stupid-guests-pay.md, .github/workflows/ci.yaml, .github/workflows/release.yaml, packages/rubin-style-dictionary/package.json
- Use a custom GITHUB_TOKEN for the changesets/action in order to trigger the Docker release workflow for Squareone.
- Associate rubin-style-dictionary with the lsst-sqre/squareone monorepo in its package.json metadata.
=> DM-40262: Tweaks to the release process

.changeset/polite-numbers-swim.md, .github/workflows/docker-release.yaml
The tag push event wasn't triggering the workflow (potentially because
the tag was being created via the API?). Instead we'll try triggering
the Docker releases from the GitHub Release event.
=> DM-40262: Trigger Docker release on the release [published]

.changeset/brown-dingos-mix.md, .changeset/chatty-bikes-unite.md, .changeset/seven-maps-drum.md, apps/squareone/package.json, apps/squareone/src/components/Button/Button.js, apps/squareone/src/components/TimesSquareApp/TimesSquareApp.js, apps/squareone/src/components/TimesSquareGitHubPagePanel/ExecStats.js, apps/squareone/src/components/TimesSquareGitHubPagePanel/ExecStats.stories.js, apps/squareone/src/components/TimesSquareGitHubPagePanel/TimesSquareGitHubPagePanel.js, apps/squareone/src/components/TimesSquareHtmlEventsProvider/TimesSquareHtmlEventsProvider.js, apps/squareone/src/components/TimesSquareHtmlEventsProvider/index.js, apps/squareone/src/components/TimesSquareNotebookViewer/TimesSquareNotebookViewer.js, apps/squareone/src/components/TimesSquareNotebookViewer/useHtmlStatus.js, apps/squareone/src/components/TimesSquareParameters/TimesSquareParameters.js, apps/squareone/src/components/TimesSquareUrlParametersProvider/TimesSquareUrlParametersProvider.js, apps/squareone/src/components/TimesSquareUrlParametersProvider/index.js, apps/squareone/src/hooks/useTimesSquarePage.js, apps/squareone/src/pages/times-square/github-pr/[owner]/[repo]/[commit]/[...tsSlug].js, apps/squareone/src/pages/times-square/github/[...tsSlug].js, apps/squareone/src/pages/times-square/index.js, packages/squared/package.json, pnpm-lock.yaml
=> DM-43461: Enable background page recomputation in Times Square

.changeset/calm-items-think.md, .changeset/smart-pandas-deny.md, apps/squareone/package.json, apps/squareone/src/components/TimesSquareGitHubPagePanel/GitHubEditLink.js, apps/squareone/src/components/TimesSquareGitHubPagePanel/GitHubEditLink.stories.js, apps/squareone/src/components/TimesSquareGitHubPagePanel/IpynbDownloadLink.js, apps/squareone/src/components/TimesSquareGitHubPagePanel/TimesSquareGitHubPagePanel.js, apps/squareone/src/hooks/useTimesSquarePage.js, apps/squareone/src/styles/icons.js, pnpm-lock.yaml
This component links to the notebook in GitHub. Currently it assumes we're referencing the "main" branch; to fix that we'd have to store the default branch in Times Square to serve from its API.
Also include a link to download the notebook file with parameters filled in so that a user can pick the analysis in their own JupyterLab pod.
=> DM-43859: Include link to notebook on GitHub

.changeset/many-moles-join.md, packages/squared/src/components/GafaelfawrUserMenu/GafaelfawrUserMenu.stories.tsx, packages/squared/src/components/GafaelfawrUserMenu/Menu.tsx
This disables opening the navigation menu on hover, and instead requires the user to click on the trigger to open it. This is generally a better UX because it means that the menu stays open without the user needing to have precise mousing.
=> DM-44392: Prevent opening/closing GafaelfawrUserMenu on hover.

.changeset/orange-roses-provide.md, apps/squareone/src/components/Header/UserMenu.js
This fixes a regression caused when migrating to the new GafaelfawrUserMenu.
=> DM-44392: Change Account settings item back to title case

.changeset/eight-crabs-develop.md, apps/squareone/package.json, apps/squareone/squareone.config.schema.json, apps/squareone/src/pages/_app.js, pnpm-lock.yaml
This enables sending analytics for Squareone usage to [Plausible.io](https://plausible.io).
Setting up Plausible's tracking is done with https://github.com/4lejandrito/next-plausible
Tracking is optional; by not setting the plausibleDomain configuration the tracking is not enabled.
=> DM-45786: Add Plausible.io tracking support

.changeset/early-eagles-vanish.md, .changeset/perfect-garlics-bathe.md, .changeset/sixty-books-sneeze.md, apps/squareone/.storybook/preview.js, apps/squareone/squareone.config.schema.json, apps/squareone/squareone.config.yaml, apps/squareone/src/components/TimesSquareApp/Sidebar.js, apps/squareone/src/lib/utils/docsUrls.js, apps/squareone/src/pages/_app.js, apps/squareone/src/styles/icons.js, packages/global-css/src/next.css, packages/global-css/src/tokens.css, packages/squared/package.json, packages/squared/src/components/IconPill/IconPill.stories.tsx, packages/squared/src/components/IconPill/IconPill.tsx, packages/squared/src/components/IconPill/index.ts, packages/squared/src/index.ts, pnpm-lock.yaml
- The Times Square UI includes a link to its environment-specific user documentation
- The new configuration `docsBaseUrl` sets the root of the rsp.lsst.io docs for that environment (e.g. can be `https://rsp.lsst.io/v/usdfprod` for USDF). We use that configuration to compute the instance-relevant link to the user documentation for Times Square.
- The Squared component library includes  a new reusable component called the IconPill that provides an inline pill-shaped link. The pill's content includes an icon specified from FontAwesome and text content.
- The CSS custom properties formerly from the Squareone app's `globals.css` file are now included in the global-css package. This allows these custom properties to be used by components in the Squared package.
=> DM-48448: Add link to user docs from Times Square UI

.changeset/nice-lizards-mate.md, apps/squareone/src/components/TimesSquareHtmlEventsProvider/TimesSquareHtmlEventsProvider.js
The Times Square UI now closes its connection to the `/times-square/pages/:page/html/events?<qs>` SSE endpoint once the page instance's execution status is "complete" and the HTML hash is computed. With this change, the Times Square UI reduces its ongoing load on the API and also reduces network usage. The HTML page will still update to the latest version because the iframe component pings the Times Square `pages/:page/htmlstatus?<qs>` endpoint. We may back this off or convert the page update to an opt-in future in the future to further reduce network and API load from the front-end.
=> DM-48557: Improve efficiency of Times Square's use of the /events SSE endpoint

.changeset/seven-buckets-brake.md, apps/squareone/package.json, apps/squareone/src/components/TimesSquareParameters/ParameterInput.js, apps/squareone/src/components/TimesSquareParameters/TimesSquareParameters.js, pnpm-lock.yaml
Times Square now supports string parameters with date and date-time formats. The error messages remind the user about the ISO 8601 date / datetime formats. A timezone is required for date-time parameters.
=> DM-48923: Provide Times Square support for date and date-time parameters

.changeset/eleven-cycles-study.md, .changeset/tiny-ads-send.md, .github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/run-chromatic.yaml, apps/squareone/src/components/BroadcastBannerStack/BroadcastBanner.js, apps/squareone/src/components/BroadcastBannerStack/BroadcastBanner.stories.jsx, packages/rubin-style-dictionary/src/color/orange.yaml
This notice category replaces the earlier default ("maintenance") and is orange. Another new category, "outage", takes the red colour. This change is driven by Semaphore at https://github.com/lsst-sqre/semaphore/pull/109
=> DM-51547: Reorganize broadcast banners

.changeset/fast-snakes-warn.md, .changeset/fix-next-sentry-compatibility.md, .changeset/nice-goats-draw.md, .claude/.gitignore, CLAUDE.md, apps/squareone/next.config.js, apps/squareone/package.json, pnpm-lock.yaml
- Update Next to 12.3.5 as an initial dependency upgrade project step
- Resolve compatibility between the sentry sdk and Next 12 by downgrading to v7 and also filtering out deprecated configuration properties.
=> DM-52127: Update Next to 12.3.5

.changeset/update-typescript-target-es2022.md, packages/tsconfig/next.json, packages/tsconfig/react-library.json
Updates shared TypeScript configurations to use ES2022 target and
library support for better compatibility with Node 22, React 19, and
Next.js 15. This enables modern JavaScript features like top-level
await, private fields, and logical assignment operators.
Changes:
- packages/tsconfig/next.json: target es2017 → ES2022
- packages/tsconfig/react-library.json: target es6 → ES2022
- Update lib arrays to include ES2022 features
Includes changeset for minor version bump of @lsst-sqre/tsconfig.
=> Update TypeScript target to ES2022
